In [1]:
import pandas as pd

In [5]:
math_written_df = pd.read_csv('../../data/umimematikucz-system_written_answer_data.csv', delimiter = ';')
math_resource_df = pd.read_csv('../../data/umimematikucz-system_resource_set.csv', delimiter = ';')
inf_binary_df = pd.read_csv('../../data/umimeprogramovatcz-system_binary_choice_data.csv', delimiter = ';')
inf_resource_df = pd.read_csv('../../data/umimeprogramovatcz-system_resource_set.csv', delimiter = ';')

In [6]:
math_written_df

,id,rs,difficultyRank,question,commonWrongAnswer,translation,explanation,created,lastUpdate,masterUpdated,checkTranslate,visible
0,1,1099,1,"[[""latex"",""1+1""], [""input"",{""answer"":[""2""],""st...",1,NaN,NaN,2017-05-15 11:41:42,2025-02-20 21:16:49,0000-00-00 00:00:00,0,1
1,2,1103,1,"[[""latex"",""2-1""],[""input"",{""answer"":[""1""],""sty...",3,NaN,NaN,2017-05-15 11:41:42,2017-05-15 11:41:42,0000-00-00 00:00:00,0,1
2,3,1099,1,"[[""latex"",""1+2""],[""input"",{""answer"":[""3""],""sty...",2,NaN,NaN,2017-05-15 11:41:42,2017-05-15 11:41:42,0000-00-00 00:00:00,0,1
3,4,1103,1,"[[""latex"",""3-2""],[""input"",{""answer"":[""1""],""sty...",5,NaN,NaN,2017-05-15 11:41:42,2017-05-15 11:41:42,0000-00-00 00:00:00,0,1
4,5,1099,1,"[[""latex"",""1+3""],[""input"",{""answer"":[""4""],""sty...",3,NaN,NaN,2017-05-15 11:41:42,2017-05-15 11:41:42,0000-00-00 00:00:00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
14249,16148,773,2,"[[""latex"",""7 \\cdot (2x +2)=-42""], [""input"",{""...",NaN,NaN,"[[""latex"",""7 \\cdot (2x +2)=-42""], [""text"","" V...",2026-02-17 11:09:09,2026-02-17 11:09:09,0000-00-00 00:00:00,0,1
14250,16149,773,2,"[[""latex"",""(x -5):7=3""], [""input"",{""answer"":[""...",NaN,NaN,"[[""latex"",""(x -5):7=3""], [""text"","" Vynásobíme ...",2026-02-17 11:09:11,2026-02-17 11:09:11,0000-00-00 00:00:00,0,1
14251,16150,773,2,"[[""latex"",""3=(x -5):2""], [""input"",{""answer"":[""...",NaN,NaN,"[[""latex"",""3=(x -5):2""], [""text"","" Vynásobíme ...",2026-02-17 11:09:12,2026-02-17 11:09:12,0000-00-00 00:00:00,0,1
14252,16151,773,2,"[[""latex"",""(-2 + x):3=6""], [""input"",{""answer"":...",NaN,NaN,"[[""latex"",""(-2 + x):3=6""], [""text"","" Vynásobím...",2026-02-17 11:09:13,2026-02-17 11:09:13,0000-00-00 00:00:00,0,1
14253,16152,773,2,"[[""latex"",""-2=(-3 + x):6""], [""input"",{""answer""...",NaN,NaN,"[[""latex"",""-2=(-3 + x):6""], [""text"","" Vynásobí...",2026-02-17 11:09:14,2026-02-17 11:09:14,0000-00-00 00:00:00,0,1

In [7]:
math_resource_df

,id,parent,type,name,shortName,shortcut,explanation,specs,aggregationType
0,226,15,binaryChoice,NaN,NaN,bc-pocitani-do-100,NaN,NaN,basic
1,227,15,binaryChoice,"[[""text"",""Odhad počtu teček""]]",NaN,bc-odhad-poctu-tecek,NaN,NaN,basic
2,228,16,binaryChoice,NaN,NaN,bc-porovnavani-cisel-do-100,NaN,NaN,basic
3,229,158,binaryChoice,NaN,NaN,bc-cisla-slovne,NaN,NaN,basic
4,230,151,binaryChoice,NaN,NaN,bc-zaokrouhlovani-na-desitky-a-stovky,NaN,NaN,basic
...,...,...,...,...,...,...,...,...,...
735,1237,468,binaryChoice,NaN,NaN,bc-development-02-2026,NaN,NaN,basic
736,1238,152,binaryChoice,NaN,NaN,bc-zaokrouhlovani-desetinnych-cisel-desetinna-...,NaN,NaN,basic
737,1239,152,binaryChoice,NaN,NaN,bc-zaokrouhlovani-desetinnych-cisel-na-desitky...,NaN,NaN,basic
738,1240,534,writtenAnswer,NaN,NaN,wa-nasobilky-jednocifernych-cisel-a-10-mix,NaN,"{""rs"":[""wa-mala-nasobilka-cislo-2"",""wa-mala-na...",mix
739,1241,534,writtenAnswer,NaN,NaN,wa-nasobilky-cisel-2-az-5-mix,NaN,"{""rs"":[""wa-mala-nasobilka-cislo-2"",""wa-mala-na...",mix